spring.application.name=LeLo
spring.datasource.url=jdbc:mysql://localhost:3306/ecom
spring.datasource.username=root
spring.datasource.password=saMI72

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.servlet.session.timeout=30m

# JSP
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# Tells Spring where to look for the error page
server.error.path=/error